In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn import svm

## Question 1

In [2]:
#Question 1
#By using normal equations
x1 = np.zeros(5)
x2 = np.zeros(5)
for i in range(1,6):
    x1[i-1]=(np.cos(2*i))
    x2[i-1]=(np.cos(5*i))
y = np.array([2.4,1.3,-0.5,1.6,2.8])

x1_ = x1.reshape(-1,1)
x2_ = x2.reshape(-1,1)
y_ = y.reshape(-1,1)
X = np.hstack([np.ones(5).reshape(-1,1),x1_,x2_])
#print(X.shape)
print("The input dataset: ", X)
print("The output vector: ", y_)
#By using normal equation
theta = np.linalg.inv(X.T@X)@X.T@y
print("The weights according to normal equations: ", theta)

The input dataset:  [[ 1.         -0.41614684  0.28366219]
 [ 1.         -0.65364362 -0.83907153]
 [ 1.          0.96017029 -0.75968791]
 [ 1.         -0.14550003  0.40808206]
 [ 1.         -0.83907153  0.99120281]]
The output vector:  [[ 2.4]
 [ 1.3]
 [-0.5]
 [ 1.6]
 [ 2.8]]
The weights according to normal equations:  [ 1.24959219 -1.17768804  0.75334737]


In [3]:
#By using scikit learn
model = LinearRegression()
model.fit(X[:,1:],y)
print("The model weights according to sklearn: ", model.coef_)
print("The model intercept according to sklearn: ", model.intercept_)
#print(model.coef_,model.intercept_)

The model weights according to sklearn:  [-1.17768804  0.75334737]
The model intercept according to sklearn:  1.2495921919356916


## Question 2


In [4]:
#KNN classifier using sklearn here label A,B is taken as 0,1
x1 = np.array([2,4,1,5,3,6,5,2,3,4])
x2 = np.array([3,2,1,4,2,5,2,4,5,4])
#The categorical data is turned into binary data with 0=A and 1=B
y = np.array([0,1,0,1,0,1,1,0,0,1])
X = np.hstack([x1.reshape(-1,1),x2.reshape(-1,1)])
y_ = y.reshape(-1,)
print("The input datasaet: ", X)
print("The output vectore: ", y)
query=[[4,3]] #The query point
model2 = KNeighborsClassifier(n_neighbors=1)
model2.fit(X,y_)
print("The class prediction of the query according to KNN classifier with n=1: ", model2.predict(query))
model3 = KNeighborsClassifier(n_neighbors=3)
model3.fit(X,y_)
print("The class prediction of the query according to KNN classifier with n=3: ", model2.predict(query))

The input datasaet:  [[2 3]
 [4 2]
 [1 1]
 [5 4]
 [3 2]
 [6 5]
 [5 2]
 [2 4]
 [3 5]
 [4 4]]
The output vectore:  [0 1 0 1 0 1 1 0 0 1]
The class prediction of the query according to KNN classifier with n=1:  [1]
The class prediction of the query according to KNN classifier with n=3:  [1]


## Question 3

In [5]:
#The input is same as the previous question
#The output must be changed to +1 and -1 respectively with A=+1 and B=-1
X_svm = X
y_svm = np.array([1,-1,1,-1,1,-1,-1,1,1,-1,])
y_svm_ = y_svm.reshape(-1,)

svm_model = svm.SVC(kernel='linear')
svm_model.fit(X_svm,y_svm_)
print("The support vectors are ", svm_model.support_vectors_)
print("The weight coefficients are: ", svm_model.coef_)
print("The bias coefficients are: ", svm_model.intercept_)
print("The number of support vectors for each class: ", svm_model.n_support_)
print("The decision functions for the samples are: ", svm_model.decision_function(X_svm))
print("The prediction for a point (4,3): ", svm_model.predict([[4,3]]))

The support vectors are  [[4. 2.]
 [4. 4.]
 [3. 2.]
 [3. 5.]]
The weight coefficients are:  [[-1.7  0.1]]
The bias coefficients are:  [5.6]
The number of support vectors for each class:  [2 2]
The decision functions for the samples are:  [ 2.5 -1.   4.  -2.5  0.7 -4.1 -2.7  2.6  1.  -0.8]
The prediction for a point (4,3):  [-1]
